// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: basic-grpc.proto

package basicgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=City,proto3" json:"City,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	mi := &file_basic_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basic_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_basic_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type WeatherReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=City,proto3" json:"City,omitempty"`
	Temperature   string                 `protobuf:"bytes,2,opt,name=Temperature,proto3" json:"Temperature,omitempty"`
	Condition     string                 `protobuf:"bytes,3,opt,name=Condition,proto3" json:"Condition,omitempty"`
	Humidity      string                 `protobuf:"bytes,4,opt,name=Humidity,proto3" json:"Humidity,omitempty"`
	WindSpeed     string                 `protobuf:"bytes,5,opt,name=WindSpeed,proto3" json:"WindSpeed,omitempty"`
	Precipitation string                 `protobuf:"bytes,6,opt,name=Precipitation,proto3" json:"Precipitation,omitempty"`
	Pressure      string                 `protobuf:"bytes,7,opt,name=Pressure,proto3" json:"Pressure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherReply) Reset() {
	*x = WeatherReply{}
	mi := &file_basic_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherReply) ProtoMessage() {}

func (x *WeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_basic_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherReply.ProtoReflect.Descriptor instead.
func (*WeatherReply) Descriptor() ([]byte, []int) {
	return file_basic_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherReply) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *WeatherReply) GetTemperature() string {
	if x != nil {
		return x.Temperature
	}
	return ""
}

func (x *WeatherReply) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *WeatherReply) GetHumidity() string {
	if x != nil {
		return x.Humidity
	}
	return ""
}

func (x *WeatherReply) GetWindSpeed() string {
	if x != nil {
		return x.WindSpeed
	}
	return ""
}

func (x *WeatherReply) GetPrecipitation() string {
	if x != nil {
		return x.Precipitation
	}
	return ""
}

func (x *WeatherReply) GetPressure() string {
	if x != nil {
		return x.Pressure
	}
	return ""
}

type StockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockRequest) Reset() {
	*x = StockRequest{}
	mi := &file_basic_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockRequest) ProtoMessage() {}

func (x *StockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basic_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockRequest.ProtoReflect.Descriptor instead.
func (*StockRequest) Descriptor() ([]byte, []int) {
	return file_basic_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *StockRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type StockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockReply) Reset() {
	*x = StockReply{}
	mi := &file_basic_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReply) ProtoMessage() {}

func (x *StockReply) ProtoReflect() protoreflect.Message {
	mi := &file_basic_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReply.ProtoReflect.Descriptor instead.
func (*StockReply) Descriptor() ([]byte, []int) {
	return file_basic_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *StockReply) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockReply) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StockReply) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_basic_grpc_proto protoreflect.FileDescriptor

const file_basic_grpc_proto_rawDesc = "" +
	"\n" +
	"\x10basic-grpc.proto\x12\tbasicgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\x0eWeatherRequest\x12\x12\n" +
	"\x04City\x18\x01 \x01(\tR\x04City\"\xde\x01\n" +
	"\fWeatherReply\x12\x12\n" +
	"\x04City\x18\x01 \x01(\tR\x04City\x12 \n" +
	"\vTemperature\x18\x02 \x01(\tR\vTemperature\x12\x1c\n" +
	"\tCondition\x18\x03 \x01(\tR\tCondition\x12\x1a\n" +
	"\bHumidity\x18\x04 \x01(\tR\bHumidity\x12\x1c\n" +
	"\tWindSpeed\x18\x05 \x01(\tR\tWindSpeed\x12$\n" +
	"\rPrecipitation\x18\x06 \x01(\tR\rPrecipitation\x12\x1a\n" +
	"\bPressure\x18\a \x01(\tR\bPressure\"&\n" +
	"\fStockRequest\x12\x16\n" +
	"\x06Symbol\x18\x01 \x01(\tR\x06Symbol\"t\n" +
	"\n" +
	"StockReply\x12\x16\n" +
	"\x06Symbol\x18\x01 \x01(\tR\x06Symbol\x12\x14\n" +
	"\x05Price\x18\x02 \x01(\x02R\x05Price\x128\n" +
	"\tTimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp2\x91\x01\n" +
	"\vGeneralInfo\x12B\n" +
	"\n" +
	"GetWeather\x12\x19.basicgrpc.WeatherRequest\x1a\x17.basicgrpc.WeatherReply\"\x00\x12>\n" +
	"\bGetStock\x12\x17.basicgrpc.StockRequest\x1a\x15.basicgrpc.StockReply\"\x000\x01B=Z;github.com/TunaCici/Mhysa/Experimental/basic-grpc;basicgrpcb\x06proto3"

var (
	file_basic_grpc_proto_rawDescOnce sync.Once
	file_basic_grpc_proto_rawDescData []byte
)

func file_basic_grpc_proto_rawDescGZIP() []byte {
	file_basic_grpc_proto_rawDescOnce.Do(func() {
		file_basic_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basic_grpc_proto_rawDesc), len(file_basic_grpc_proto_rawDesc)))
	})
	return file_basic_grpc_proto_rawDescData
}

var file_basic_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_basic_grpc_proto_goTypes = []any{
	(*WeatherRequest)(nil),        // 0: basicgrpc.WeatherRequest
	(*WeatherReply)(nil),          // 1: basicgrpc.WeatherReply
	(*StockRequest)(nil),          // 2: basicgrpc.StockRequest
	(*StockReply)(nil),            // 3: basicgrpc.StockReply
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_basic_grpc_proto_depIdxs = []int32{
	4, // 0: basicgrpc.StockReply.Timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: basicgrpc.GeneralInfo.GetWeather:input_type -> basicgrpc.WeatherRequest
	2, // 2: basicgrpc.GeneralInfo.GetStock:input_type -> basicgrpc.StockRequest
	1, // 3: basicgrpc.GeneralInfo.GetWeather:output_type -> basicgrpc.WeatherReply
	3, // 4: basicgrpc.GeneralInfo.GetStock:output_type -> basicgrpc.StockReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_basic_grpc_proto_init() }
func file_basic_grpc_proto_init() {
	if File_basic_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_grpc_proto_rawDesc), len(file_basic_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basic_grpc_proto_goTypes,
		DependencyIndexes: file_basic_grpc_proto_depIdxs,
		MessageInfos:      file_basic_grpc_proto_msgTypes,
	}.Build()
	File_basic_grpc_proto = out.File
	file_basic_grpc_proto_goTypes = nil
	file_basic_grpc_proto_depIdxs = nil
}
